Vagrant.configure("2") do |config|

  config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "controller"
  end

  config.vm.box = "generic/debian12"

  # Provision the machine with Ansible installation
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y software-properties-common
    sudo apt-add-repository --yes --update ppa:ansible/ansible
    sudo apt-get install -y ansible
  SHELL

end
